apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: adhar-controller
rules:
  - apiGroups: ["platform.adhar.io"]
    resources: ["adharplatforms"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["platform.adhar.io"]
    resources: ["adharplatforms/status"]
    verbs: ["get", "update", "patch"]
  - apiGroups: ["platform.adhar.io"]
    resources: ["adharplatforms/finalizers"]
    verbs: ["update"]
  - apiGroups: ["apps"]
    resources: ["deployments", "statefulsets", "daemonsets"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: [""]
    resources:
      [
        "services",
        "configmaps",
        "secrets",
        "namespaces",
        "persistentvolumeclaims",
        "serviceaccounts",
      ]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["networking.k8s.io"]
    resources: ["ingresses"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["rbac.authorization.k8s.io"]
    resources: ["clusterroles", "clusterrolebindings", "roles", "rolebindings"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: adhar-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: adhar-controller
subjects:
  - kind: ServiceAccount
    name: default
    namespace: adhar-system
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argocd-server-ingress
  namespace: adhar-system
  labels:
    app.kubernetes.io/name: argocd-server
    app.kubernetes.io/instance: argo-cd
    app.kubernetes.io/component: server
    app.kubernetes.io/part-of: argocd
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - adhar.localtest.me
      secretName: adhar-localtest-tls
  rules:
    - host: adhar.localtest.me
      http:
        paths:
          - path: /argocd
            pathType: Prefix
            backend:
              service:
                name: argo-cd-argocd-server
                port:
                  number: 443
