---
# Source: ingress-nginx/templates/controller-configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    helm.sh/chart: ingress-nginx-4.6.1
    app.kubernetes.io/name: ingress-nginx-platform
    app.kubernetes.io/instance: ingress-nginx-platform
    app.kubernetes.io/version: "1.7.1"
    app.kubernetes.io/part-of: ingress-nginx-platform
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: controller
  name: ingress-nginx-platform-controller
  namespace: ingress
data:
  allow-snippet-annotations: "true"
  client-body-timeout: "5"
  client-header-timeout: "5"
  client-max-body-size: "0"
  disable-ipv6: "true"
  enable-modsecurity: "false"
  enable-opentelemetry: "false"
  enable-owasp-modsecurity-crs: "true"
  hsts: "true"
  http2-max-field-size: "64k"
  http2-max-header-size: "128k"
  large-client-header-buffers: "8 16k"
  log-format-upstream: "$proxy_protocol_addr - $remote_user [$time_local] $host \"$request\" $status $body_bytes_sent \"$http_referer\" \"$http_user_agent\" $request_length $request_time [$proxy_upstream_name] [$proxy_alternative_upstream_name] $upstream_addr $upstream_response_length $upstream_response_time $upstream_status $req_id"
  opentelemetry-config: "/etc/nginx/opentelemetry.toml"
  opentelemetry-operation-name: "HTTP $request_method $service_name $uri"
  opentelemetry-trust-incoming-span: "true"
  otel-max-export-batch-size: "512"
  otel-max-queuesize: "2048"
  otel-sampler: "AlwaysOn"
  otel-sampler-parent-based: "true"
  otel-sampler-ratio: "0.01"
  otel-schedule-delay-millis: "5000"
  otel-service-name: "nginx-platform"
  otlp-collector-host: "otel-collector-collector.otel.svc"
  otlp-collector-port: "4317"
  proxy-body-size: "1024m"
  proxy-buffer-size: "16k"
  proxy-buffers-number: "8"
  ssl-redirect: "true"
  use-forwarded-headers: "false"
  use-proxy-protocol: "true"
