---
# Source: ingress-nginx/templates/controller-hpa.yaml
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  annotations:
  labels:
    helm.sh/chart: ingress-nginx-4.6.1
    app.kubernetes.io/name: ingress-nginx-platform
    app.kubernetes.io/instance: ingress-nginx-platform
    app.kubernetes.io/version: "1.7.1"
    app.kubernetes.io/part-of: ingress-nginx-platform
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: controller
  name: ingress-nginx-platform-controller
  namespace: ingress
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ingress-nginx-platform-controller
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 75
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 60
