---
# Source: ingress-nginx/templates/controller-rolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    helm.sh/chart: ingress-nginx-4.6.1
    app.kubernetes.io/name: ingress-nginx-platform
    app.kubernetes.io/instance: ingress-nginx-platform
    app.kubernetes.io/version: "1.7.1"
    app.kubernetes.io/part-of: ingress-nginx-platform
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: controller
  name: ingress-nginx-platform
  namespace: ingress
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ingress-nginx-platform
subjects:
  - kind: ServiceAccount
    name: ingress-nginx-platform
    namespace: "ingress"
