---
# Source: ingress-nginx/templates/controller-poddisruptionbudget.yaml
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  labels:
    helm.sh/chart: ingress-nginx-4.6.1
    app.kubernetes.io/name: ingress-nginx-platform
    app.kubernetes.io/instance: ingress-nginx-platform
    app.kubernetes.io/version: "1.7.1"
    app.kubernetes.io/part-of: ingress-nginx-platform
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: controller
  name: ingress-nginx-platform-controller
  namespace: ingress
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: ingress-nginx-platform
      app.kubernetes.io/instance: ingress-nginx-platform
      app.kubernetes.io/component: controller
  minAvailable: 1
