apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: adhar-console
  namespace: argocd
  labels:
    env: dev
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: adhar-system
    server: "https://kubernetes.default.svc"
  source:
    repoURL: cnoe://adhar-console/manifests
    targetRevision: HEAD
    path: "."
  project: default
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
