apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  labels:
    env: dev
  name: backstage-templates
  namespace: adhar-system
spec:
  destination:
    namespace: backstage
    server: https://kubernetes.default.svc
  project: default
  source:
    directory:
      exclude: catalog-info.yaml
    path: application/adhar-templates
    repoURL: http://gitea-argocd.adhar-system.svc.cluster.local:3000/gitea_admin/packages
    targetRevision: main
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
