apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: local-manifests
  namespace: adhar-system
spec:
  generators:
    - matrix:
        generators:
          - git:
              files:
                - path: "**/config.yaml"
              repoURL: http://gitea-http-clusterip.adhar-system.svc.cluster.local:3000/gitea_admin/environments
              revision: HEAD
          - list:
              elementsYaml: "{{ .packages | toJson }}"
            selector:
              matchExpressions:
                - key: install
                  operator: In
                  values:
                    - "true"
                - key: isChart
                  operator: In
                  values:
                    - "false"
  goTemplate: true
  goTemplateOptions:
    - missingkey=error
  template:
    metadata:
      finalizers:
        - resources-finalizer.argocd.argoproj.io
      labels:
        environment: "{{ .environment }}"
      name: "{{ .name }}"
    spec:
      destination:
        namespace: "{{ .namespace }}"
        server: https://kubernetes.default.svc
      project: default
      sources:
        - path: "{{ .manifestPath }}"
          repoURL: http://gitea-http-clusterip.adhar-system.svc.cluster.local:3000/gitea_admin/packages
          targetRevision: HEAD
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        retry:
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 3m0s
          limit: 30
        syncOptions:
          - Replace=true
          - CreateNamespace=true
          - ServerSideApply=true
