apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: helm-charts
  namespace: adhar-system
spec:
  generators:
    - matrix:
        generators:
          - git:
              files:
                - path: "**/config.yaml"
              repoURL: https://github.com/adhar-platform/platform-stack
              revision: main
          - list:
              elementsYaml: "{{ .packages | toJson }}"
            selector:
              matchExpressions:
                - key: install
                  operator: In
                  values:
                    - "true"
                - key: isChart
                  operator: In
                  values:
                    - "true"
  goTemplate: true
  goTemplateOptions:
    - missingkey=error
  template:
    metadata:
      finalizers:
        - resources-finalizer.argocd.argoproj.io
      labels:
        adhar.io/package-name: adhar-stack
        environment: "{{ .environment }}"
      name: "{{ .name }}"
    spec:
      destination:
        namespace: "{{ .namespace }}"
        server: https://kubernetes.default.svc
      project: default
      sources:
        - helm:
            valueFiles:
              - values.yaml
          path: "{{ .manifestPath }}"
          repoURL: https://github.com/adhar-platform/platform-stack
          targetRevision: main
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        retry:
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 3m0s
          limit: 30
        syncOptions:
          - Replace=true
          - CreateNamespace=true
          - ServerSideApply=true
