apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: local-manifests
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions:
    - missingkey=error
  generators:
    - matrix:
        generators:
          - git:
              repoURL: "adhar://environments"
              revision: HEAD
              files:
                - path: "**/config.yaml"
          - list:
              elementsYaml: "{{ .packages | toJson }}"
            selector:
              matchExpressions:
                - key: install
                  operator: In
                  values:
                    - "true"
                - key: isChart
                  operator: In
                  values:
                    - "false"
  template:
    metadata:
      name: "{{ .name }}"
      labels:
        environment: "{{ .environment }}"
      finalizers:
        - resources-finalizer.argocd.argoproj.io
    spec:
      project: default
      sources:
        - repoURL: "adhar://packages"
          targetRevision: HEAD
          path: "{{ .manifestPath }}"
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{ .namespace }}"
      syncPolicy:
        syncOptions:
          - Replace=true
          - CreateNamespace=true
          - ServerSideApply=true
        automated:
          selfHeal: true
          prune: true
        retry:
          limit: 30
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 3m0s