apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudnative-pg
  namespace: argocd
  labels:
    env: dev
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: 'https://cloudnative-pg.github.io/charts'
      targetRevision: 0.21.4
      helm:
        releaseName: cnpg
        valueFiles:
          - $values/values.yaml
      chart: cloudnative-pg
    - repoURL: cnoe://cloudnative-pg
      targetRevision: HEAD
      ref: values
  destination:
    server: "https://kubernetes.default.svc"
    namespace: cloudnative-pg
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
