apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openfunction
  namespace: argocd
  labels:
    env: dev
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: 'https://openfunction.github.io/charts/'
      targetRevision: 0.7.0
      helm:
        releaseName: openfunction
        valueFiles:
          - $values/helm/values.yaml
      chart: openfunction
    - repoURL: cnoe://openfunction
      targetRevision: HEAD
      ref: values
  destination:
    server: "https://kubernetes.default.svc"
    namespace: argocd
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
