project_name: adhar

before:
  hooks:
    - go mod tidy
release:
  # Mark nightly build as prerelease based on tag
  prerelease: auto

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -X github.com/adhar-io/adhar/pkg/cmd/version.idpbuilderVersion={{ .Version }}
      - -X github.com/adhar-io/adhar/pkg/cmd/version.gitCommit={{ .FullCommit }}
      - -X github.com/adhar-io/adhar/pkg/cmd/version.buildDate={{ .CommitDate }}
      - -w
      - -s
    binary: adhar
    ignore:
      - goos: linux
        goarch: '386'
brews:
  - name: idpbuilder
    homepage: "https://cnoe.io"
    repository:
      owner: cnoe-io
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TOKEN }}"
    commit_author:
      name: "CNOEAutomation"
      email: "noreply@cnoe.io"
    directory: Formula
    install: |
      bin.install "idpbuilder"
    test: |
      system "#{bin}/idpbuilder --version"
archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}-{{ .Os }}-{{ .Arch }}
checksum:
  name_template: 'checksums.txt'
snapshot:
  version_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

