{{- $kms := .Values.kms | default dict }}
{{- $imageName := .Values.imageName | default "adhar" }}
{{- $version := .Values.adhar.version | default .Chart.AppVersion }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "adhar.fullname" . }}
  labels: {{- include "adhar.labels" . | nindent 4 }}
spec:
  backoffLimit: 2
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations: {{- toYaml . | nindent 8 }}
      {{- end }}
      labels: {{- include "adhar.selectorLabels" . | nindent 8 }}
    spec:
      restartPolicy: Never
      serviceAccountName: {{ include "adhar.fullname" . }}
      securityContext:
        runAsNonRoot: true
        runAsUser: 999
        runAsGroup: 999
        fsGroup: 3000
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: install
          image: {{ $imageName }}:{{ $version }}
          imagePullPolicy: {{ ternary "IfNotPresent" "Always" (regexMatch "^v\\d" $version) }}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            runAsNonRoot: true
          resources:
            limits:
              memory: 2Gi
              cpu: '2'
            requests:
              memory: 1Gi
              cpu: '1'
          command: [bash, -c]
          args:
            - |
              kubectl create ns adhar &> /dev/null
              binzx/adhar validate-cluster && binzx/adhar bootstrap && binzx/adhar apply
          env:
            - name: VERBOSITY
              value: '1'
            - name: ENV_DIR
              value: /home/app/stack/env
            - name: VALUES_INPUT
              value: /secret/values.yaml
          {{- if hasKey $kms "sops" }}
          envFrom:
            - secretRef:
                name: {{ include "adhar.fullname" . }}-sops-secrets
          {{- end }}
          volumeMounts:
            - name: adhar-values
              mountPath: /home/app/stack/env
            - name: values-secret
              mountPath: /secret
      volumes:
        - name: values-secret
          secret:
            secretName: {{ .Release.Name }}-values
        - name: adhar-values
          emptyDir: {}
      {{- if hasKey .Values "imagePullSecretNames" }}
      imagePullSecrets:
        {{- range .Values.imagePullSecretNames }}
        - name: {{ . }}
        {{- end }}
      {{- end }}
