{{- $adhar_version := .Chart.AppVersion}}
{{- $updatedValues := .Values }}
{{- if not .Values.adhar.version }}
{{- $updatedValues := merge .Values (dict "adhar" (dict "version" $adhar_version)) }}
{{- end }}

apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-values
  labels: {{- include "adhar.labels" . | nindent 4 }}
type: Opaque
data:
  values.yaml: |-
{{ $updatedValues | toYaml | b64enc | indent 4 }}