{{- $v := .Values | merge (dict) }}
{{- $ := . }}
{{- if not (eq $v.teamId "admin") }}
{{- $egressFilteringEnabled := $v | dig "networkPolicy" "egressPublic" true }}
{{- if $egressFilteringEnabled }}
---
apiVersion: networking.istio.io/v1beta1
kind: Sidecar
metadata:
  name: default
  labels: {{- include "team-ns.chart-labels" $ | nindent 4 }}
spec:
  outboundTrafficPolicy: 
    mode: REGISTRY_ONLY
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  labels:
    {{- include "team-ns.chart-labels" $ | nindent 4 }}
    prometheus: team-{{ $v.teamId }}
  name: istio-sidecars
spec:
  namespaceSelector:
    matchNames: [team-{{ $v.teamId }}]
  podMetricsEndpoints:
  - path: /stats/prometheus
    port: http-envoy-prom
  selector:
    matchLabels:
      security.istio.io/tlsMode: istio
{{- end }}
{{- end }}