---
# Source: gitea/charts/postgresql-ha/templates/pgpool/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: gitea-postgresql-ha-pgpool
  namespace: "default"
  labels:
    app.kubernetes.io/instance: gitea
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: postgresql-ha
    app.kubernetes.io/version: 4.5.5
    helm.sh/chart: postgresql-ha-15.2.3
    app.kubernetes.io/component: pgpool
type: Opaque
data:
  admin-password: "Y2hhbmdlbWUz"
