---
# Source: gitea/charts/postgresql-ha/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: gitea-postgresql-ha
  namespace: "default"
  labels:
    app.kubernetes.io/instance: gitea
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: postgresql-ha
    app.kubernetes.io/version: 17.4.0
    helm.sh/chart: postgresql-ha-15.2.3
automountServiceAccountToken: false
