apiVersion: v1
appVersion: 0.2.3
description: A place for all the Kubernetes resources which don't already have a home.
home: https://github.com/helm/charts/blob/master/incubator/raw
maintainers:
- email: josdotso@cisco.com
  name: josdotso
- email: ykuoka@gmail.com
  name: mumoshu
name: raw
version: 0.2.3
