apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: headlamp-ingress
  namespace: kube-system
  annotations:
    argocd.argoproj.io/sync-wave: "100"
spec:
  ingressClassName: "nginx"
  tls:
  - secretName: headlamp
    hosts:
    - adhar.localtest.me
  rules:
  - host: adhar.localtest.me
    http:
      paths:
      - path: /headlamp
        pathType: ImplementationSpecific
        backend:
          service:
            name: headlamp-svc
            port:
              number: 80