apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "adhar.fullname" . }}
  labels: {{- include "adhar.labels" . | nindent 4 }}
  {{- with .Values.serviceAccountAnnotations }}
  annotations: {{- toYaml . | nindent 4 }}
  {{- end }}
