---
# Secrets Composition using External Secrets Operator
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: secrets-external
  labels:
    feature: secrets
    provider: external-secrets
spec:
  compositeTypeRef:
    apiVersion: platform.adhar.io/v1alpha1
    kind: CompositeSecret
  mode: Pipeline
  pipeline:
    - step: render-external-secret
      functionRef:
        name: function-kcl
      input:
        apiVersion: krm.kcl.dev/v1alpha1
        kind: KCLRun
        spec:
          source: |
            xr = option("params").oxr
            spec = xr.spec
            name = spec.name
            namespace = spec.get("namespace", "default")
            externalSecret = spec.get("externalSecret", {})
            
            externalSecretResource = {
                apiVersion = "external-secrets.io/v1beta1"
                kind = "ExternalSecret"
                metadata = {
                    name = name
                    namespace = namespace
                }
                spec = {
                    refreshInterval = externalSecret.get("refreshInterval", "1h")
                    secretStoreRef = {
                        name = "platform-secret-store"
                        kind = "SecretStore"
                    }
                    target = {
                        name = name
                        creationPolicy = "Owner"
                    }
                    dataFrom = [{
                        extract = {
                            key = externalSecret.get("secretPath", name)
                        }
                    }]
                }
            }
            
            {
                apiVersion = "krm.kcl.dev/v1alpha1"
                kind = "ResourceList"
                items = [externalSecretResource]
            }
    
    - step: automatically-detect-ready-composed-resources
      functionRef:
        name: function-auto-ready

