---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - platform.adhar.io
  resources:
  - adharplatforms
  - custompackages
  - gitrepositories
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - platform.adhar.io
  resources:
  - adharplatforms/finalizers
  - custompackages/finalizers
  - gitrepositories/finalizers
  verbs:
  - update
- apiGroups:
  - platform.adhar.io
  resources:
  - adharplatforms/status
  - custompackages/status
  - gitrepositories/status
  verbs:
  - get
  - patch
  - update
