apiVersion: v1
kind: Secret
metadata:
  name: gcp-secret
  namespace: crossplane-system
stringData:
  creds: |
    {
      "type": "service_account",
      "project_id": "replaceme",
      "private_key_id": "replaceme",
      "private_key": "replaceme",
      "client_email": "replaceme",
      "client_id": "replaceme",
      "auth_uri": "https://accounts.google.com/o/oauth2/auth",
      "token_uri": "https://oauth2.googleapis.com/token",
      "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
      "client_x509_cert_url": "replaceme"
    }
