apiVersion: v1
kind: Service
metadata:
  name: adhar-console-svc
  labels:
    app.kubernetes.io/name: adhar-console
    app.kubernetes.io/instance: adhar-console
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http-service
  selector:
    app.kubernetes.io/name: adhar-console
    app.kubernetes.io/instance: adhar-console
