# Metrics Server Helm Chart Values

# Enable or disable kubelet insecure TLS, requirefd for kind/minikube
args:
  - --kubelet-insecure-tls

# Additional Metrics Server configuration
replicas: 1

resources:
  requests:
    memory: 64Mi
    cpu: 100m
  limits:
    memory: 128Mi
    cpu: 200m