apiVersion: platform.adhar.io/v1alpha1
kind: CustomPackage
metadata:
  labels:
    app.kubernetes.io/name: adhar
    app.kubernetes.io/managed-by: kustomize
  name: custompackage-sample
spec:
  # TODO(user): Add fields here
