apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "otomi-api.fullname" . }}-core
  labels:
{{ include "otomi-api.labels" . | indent 4 }}
data:
  core.yaml: |
    {{- toYaml .Values.core | nindent 4 }}
