apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: compositeauthstacks.platform.adhar.io
spec:
  group: platform.adhar.io
  names:
    kind: CompositeAuthStack
    plural: compositeauthstacks
  claimNames:
    kind: AuthStack
    plural: authstacks
  connectionSecretKeys:
    - issuer
    - clientId
    - clientSecret
  defaultCompositionRef:
    name: compositeauthstack-keycloak
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          required:
            - spec
          properties:
            spec:
              type: object
              required:
                - compositionSelector
                - parameters
              properties:
                compositionSelector:
                  type: object
                  properties:
                    matchLabels:
                      type: object
                      additionalProperties:
                        type: string
                  default:
                    matchLabels:
                      feature: auth
                providerConfigRef:
                  type: object
                  properties:
                    name:
                      type: string
                parameters:
                  type: object
                  required:
                    - provider
                  properties:
                    displayName:
                      type: string
                    provider:
                      type: string
                      enum:
                        - keycloak
                        - dex
                        - oauth2-proxy
                        - external
                      description: "Identity provider type"
                    realm:
                      type: string
                      description: "Keycloak realm name"
                    adminCredentialsSecretRef:
                      type: object
                      properties:
                        name:
                          type: string
                        namespace:
                          type: string
                    clients:
                      type: array
                      description: "OAuth2/OIDC clients to configure"
                      items:
                        type: object
                        required:
                          - clientId
                          - name
                        properties:
                          clientId:
                            type: string
                          name:
                            type: string
                          description:
                            type: string
                          protocol:
                            type: string
                            enum:
                              - openid-connect
                              - saml
                            default: openid-connect
                          publicClient:
                            type: boolean
                            default: false
                          redirectUris:
                            type: array
                            items:
                              type: string
                          webOrigins:
                            type: array
                            items:
                              type: string
                          scopes:
                            type: array
                            items:
                              type: string
                          roles:
                            type: array
                            items:
                              type: string
                    users:
                      type: array
                      description: "Users to create in the identity provider"
                      items:
                        type: object
                        required:
                          - username
                          - email
                        properties:
                          username:
                            type: string
                          email:
                            type: string
                          firstName:
                            type: string
                          lastName:
                            type: string
                          enabled:
                            type: boolean
                            default: true
                          emailVerified:
                            type: boolean
                            default: false
                          groups:
                            type: array
                            items:
                              type: string
                          roles:
                            type: array
                            items:
                              type: string
                          passwordSecretRef:
                            type: object
                            properties:
                              name:
                                type: string
                              namespace:
                                type: string
                              key:
                                type: string
                    groups:
                      type: array
                      description: "Groups to create"
                      items:
                        type: object
                        required:
                          - name
                        properties:
                          name:
                            type: string
                          path:
                            type: string
                          attributes:
                            type: object
                            additionalProperties:
                              type: array
                              items:
                                type: string
                    identityProviders:
                      type: array
                      description: "External identity providers to federate"
                      items:
                        type: object
                        required:
                          - alias
                          - providerId
                        properties:
                          alias:
                            type: string
                          providerId:
                            type: string
                            enum:
                              - github
                              - google
                              - oidc
                              - saml
                          displayName:
                            type: string
                          config:
                            type: object
                            additionalProperties:
                              type: string
                    rbacPolicies:
                      type: array
                      description: "RBAC policies to enforce"
                      items:
                        type: object
                        properties:
                          name:
                            type: string
                          roles:
                            type: array
                            items:
                              type: string
                          permissions:
                            type: array
                            items:
                              type: object
                              properties:
                                resource:
                                  type: string
                                actions:
                                  type: array
                                  items:
                                    type: string
                    mfaConfig:
                      type: object
                      properties:
                        enabled:
                          type: boolean
                        required:
                          type: boolean
                        otpPolicy:
                          type: object
                          properties:
                            type:
                              type: string
                              enum:
                                - totp
                                - hotp
                            algorithm:
                              type: string
                            digits:
                              type: integer
                            period:
                              type: integer
                    passwordPolicy:
                      type: object
                      properties:
                        minimumLength:
                          type: integer
                        requireUppercase:
                          type: boolean
                        requireLowercase:
                          type: boolean
                        requireDigits:
                          type: boolean
                        requireSpecialChars:
                          type: boolean
                        expiryDays:
                          type: integer
                    sessionConfig:
                      type: object
                      properties:
                        ssoSessionIdleTimeout:
                          type: integer
                        ssoSessionMaxLifespan:
                          type: integer
                        accessTokenLifespan:
                          type: integer
                    tags:
                      type: object
                      additionalProperties:
                        type: string
                writeConnectionSecretToRef:
                  type: object
                  properties:
                    namespace:
                      type: string
                      default: crossplane-system
                    name:
                      type: string
            status:
              type: object
              properties:
                phase:
                  type: string
                message:
                  type: string
                ready:
                  type: boolean
                issuer:
                  type: string
                realm:
                  type: string
                clientsConfigured:
                  type: integer
                usersConfigured:
                  type: integer
                conditions:
                  type: array
                  items:
                    type: object
                    properties:
                      type:
                        type: string
                      status:
                        type: string
                      reason:
                        type: string
                      message:
                        type: string
