---
apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: compositehealths.platform.adhar.io
spec:
  group: platform.adhar.io
  names:
    kind: CompositeHealth
    plural: compositehealths
  claimNames:
    kind: Health
    plural: healths
  versions:
  - name: v1alpha1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              name:
                type: string
              targets:
                type: array
                items:
                  type: object
                  properties:
                    name:
                      type: string
                    type:
                      type: string
                    endpoint:
                      type: string
              checks:
                type: array
                items:
                  type: object
                  properties:
                    name:
                      type: string
                    interval:
                      type: string
                    timeout:
                      type: string
              providerConfigRef:
                type: object
                properties:
                  name:
                    type: string
            required: [name]
          status:
            type: object
            properties:
              overall:
                type: string
              checks:
                type: array
                items:
                  type: object
              conditions:
                type: array
                items:
                  type: object
                  x-kubernetes-preserve-unknown-fields: true

