---
apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: compositesecrets.platform.adhar.io
spec:
  group: platform.adhar.io
  names:
    kind: CompositeSecret
    plural: compositesecrets
  claimNames:
    kind: Secret
    plural: secrets
  versions:
  - name: v1alpha1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              name:
                type: string
                description: Secret name
              type:
                type: string
                description: Secret type (generic, tls, docker-registry, service-account, external)
                enum:
                  - generic
                  - tls
                  - docker-registry
                  - service-account
                  - external
                default: generic
              namespace:
                type: string
                description: Target namespace
                default: default
              data:
                type: object
                description: Secret data (key-value pairs)
                additionalProperties:
                  type: string
              stringData:
                type: object
                description: String data (unencoded)
                additionalProperties:
                  type: string
              encryption:
                type: object
                description: Encryption configuration
                properties:
                  enabled:
                    type: boolean
                    default: true
                  provider:
                    type: string
                    description: Encryption provider (vault, aws-kms, azure-keyvault, gcp-kms)
                    enum:
                      - vault
                      - aws-kms
                      - azure-keyvault
                      - gcp-kms
                      - sealed-secrets
                  keyId:
                    type: string
              rotation:
                type: object
                description: Automatic rotation configuration
                properties:
                  enabled:
                    type: boolean
                    default: false
                  schedule:
                    type: string
                    description: Rotation schedule (cron format)
                  beforeExpiry:
                    type: string
                    description: Rotate before expiry duration
              externalSecret:
                type: object
                description: External secret store configuration
                properties:
                  enabled:
                    type: boolean
                  provider:
                    type: string
                    enum:
                      - aws-secrets-manager
                      - azure-keyvault
                      - gcp-secret-manager
                      - vault
                  secretPath:
                    type: string
                  refreshInterval:
                    type: string
                    default: 1h
              audit:
                type: object
                description: Secret access auditing
                properties:
                  enabled:
                    type: boolean
                    default: true
                  retentionDays:
                    type: integer
                    default: 90
              providerConfigRef:
                type: object
                properties:
                  name:
                    type: string
            required:
              - name
              - type
          status:
            type: object
            properties:
              secretId:
                type: string
              encrypted:
                type: boolean
              rotationStatus:
                type: object
                properties:
                  lastRotated:
                    type: string
                  nextRotation:
                    type: string
              externalSyncStatus:
                type: string
              conditions:
                type: array
                items:
                  type: object
                  x-kubernetes-preserve-unknown-fields: true
    additionalPrinterColumns:
    - name: Type
      type: string
      jsonPath: ".spec.type"
    - name: Encrypted
      type: boolean
      jsonPath: ".status.encrypted"
    - name: Last Rotated
      type: string
      jsonPath: ".status.rotationStatus.lastRotated"
    - name: Age
      type: date
      jsonPath: ".metadata.creationTimestamp"

