apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: compositesecretrotations.platform.adhar.io
spec:
  group: platform.adhar.io
  names:
    kind: CompositeSecretRotation
    plural: compositesecretrotations
  claimNames:
    kind: SecretRotation
    plural: secretrotations
  connectionSecretKeys:
    - rotationStatus
  defaultCompositionRef:
    name: compositesecretrotation-aws
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          required:
            - spec
          properties:
            spec:
              type: object
              required:
                - compositionSelector
                - parameters
              properties:
                compositionSelector:
                  type: object
                  properties:
                    matchLabels:
                      type: object
                      additionalProperties:
                        type: string
                  default:
                    matchLabels:
                      feature: secretrotation
                providerConfigRef:
                  type: object
                  properties:
                    name:
                      type: string
                parameters:
                  type: object
                  required:
                    - provider
                    - secretType
                  properties:
                    displayName:
                      type: string
                    provider:
                      type: string
                      enum:
                        - aws-secrets-manager
                        - azure-keyvault
                        - gcp-secret-manager
                        - vault
                        - external-secrets
                      description: "Secret management provider"
                    secretType:
                      type: string
                      enum:
                        - database
                        - api-key
                        - certificate
                        - ssh-key
                        - generic
                      description: "Type of secret to rotate"
                    rotationSchedule:
                      type: string
                      description: "Cron schedule for rotation (e.g., '0 0 * * 0' for weekly)"
                    rotationPeriodDays:
                      type: integer
                      minimum: 1
                      maximum: 365
                      description: "Rotation period in days"
                    automaticRotation:
                      type: boolean
                      default: true
                      description: "Enable automatic rotation"
                    secretReferences:
                      type: array
                      description: "Secrets to rotate"
                      items:
                        type: object
                        required:
                          - name
                        properties:
                          name:
                            type: string
                          namespace:
                            type: string
                          versionStages:
                            type: array
                            items:
                              type: string
                    targetServices:
                      type: array
                      description: "Services that use these secrets"
                      items:
                        type: object
                        properties:
                          name:
                            type: string
                          namespace:
                            type: string
                          restartOnRotation:
                            type: boolean
                            default: true
                    notificationConfig:
                      type: object
                      properties:
                        enabled:
                          type: boolean
                          default: true
                        channels:
                          type: array
                          items:
                            type: object
                            properties:
                              type:
                                type: string
                                enum:
                                  - slack
                                  - email
                                  - webhook
                              config:
                                type: object
                                additionalProperties:
                                  type: string
                        notifyOnSuccess:
                          type: boolean
                          default: false
                        notifyOnFailure:
                          type: boolean
                          default: true
                    preRotationHooks:
                      type: array
                      description: "Scripts to run before rotation"
                      items:
                        type: object
                        properties:
                          name:
                            type: string
                          script:
                            type: string
                          timeout:
                            type: string
                    postRotationHooks:
                      type: array
                      description: "Scripts to run after rotation"
                      items:
                        type: object
                        properties:
                          name:
                            type: string
                          script:
                            type: string
                          timeout:
                            type: string
                    retentionPolicy:
                      type: object
                      properties:
                        keepVersions:
                          type: integer
                          minimum: 1
                          default: 3
                        keepDays:
                          type: integer
                          minimum: 1
                    encryption:
                      type: object
                      properties:
                        enabled:
                          type: boolean
                          default: true
                        kmsKeyId:
                          type: string
                    auditConfig:
                      type: object
                      properties:
                        enabled:
                          type: boolean
                          default: true
                        logDestination:
                          type: string
                        retentionDays:
                          type: integer
                          default: 90
                    tags:
                      type: object
                      additionalProperties:
                        type: string
                writeConnectionSecretToRef:
                  type: object
                  properties:
                    namespace:
                      type: string
                      default: crossplane-system
                    name:
                      type: string
            status:
              type: object
              properties:
                phase:
                  type: string
                  description: "Overall phase (Active, Paused, Failed, Rotating)"
                message:
                  type: string
                ready:
                  type: boolean
                lastRotationTime:
                  type: string
                  format: date-time
                nextRotationTime:
                  type: string
                  format: date-time
                rotationCount:
                  type: integer
                currentVersion:
                  type: string
                previousVersion:
                  type: string
                failedRotations:
                  type: integer
                conditions:
                  type: array
                  items:
                    type: object
                    properties:
                      type:
                        type: string
                      status:
                        type: string
                      reason:
                        type: string
                      message:
                        type: string
