---
# Source: gitea/charts/postgresql-ha/templates/postgresql/witness-pdb.yaml
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: gitea-postgresql-ha-postgresql-witness 
  namespace: "default"
  labels:
    app.kubernetes.io/instance: gitea
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: postgresql-ha
    app.kubernetes.io/version: 17.4.0
    helm.sh/chart: postgresql-ha-15.2.3
    app.kubernetes.io/component: postgresql
    role: witness
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: gitea
      app.kubernetes.io/name: postgresql-ha
      app.kubernetes.io/component: postgresql
      role: witness
