#!/usr/bin/env bash
set -euo pipefail
# Kubeflow Pipelines (standalone) — the core ML pipeline orchestration component
# of Kubeflow. Full Kubeflow (notebooks/katib/kserve/central-dashboard) requires
# Istio + Dex + cert-manager and is far heavier than a single Kind node; the
# standalone Pipelines deployment ("platform-agnostic" env) is the portable,
# self-contained core and is what this package ships. Deploys into its own
# `kubeflow` namespace (the standalone manifests hard-code it).
#
# Bump KFP_VERSION and re-run to update. Requires kustomize (git-capable).
KFP_VERSION="${KFP_VERSION:-2.4.1}"
INSTALL_YAML="$(cd "$(dirname "$0")" && pwd)/manifests/install.yaml"
BASE="github.com/kubeflow/pipelines/manifests/kustomize"

mkdir -p "$(dirname "${INSTALL_YAML}")"
echo "# KUBEFLOW PIPELINES (standalone) INSTALL RESOURCES" >"${INSTALL_YAML}"
echo "# Auto-generated by platform/stack/packages/data/kubeflow/generate-manifests.sh" >>"${INSTALL_YAML}"
echo "# Source: kubeflow/pipelines ${KFP_VERSION} (env/platform-agnostic)" >>"${INSTALL_YAML}"

kustomize build "${BASE}/cluster-scoped-resources?ref=${KFP_VERSION}&timeout=120" >>"${INSTALL_YAML}"
echo "---" >>"${INSTALL_YAML}"
kustomize build "${BASE}/env/platform-agnostic?ref=${KFP_VERSION}&timeout=120" >>"${INSTALL_YAML}"

echo "Generated ${INSTALL_YAML} for Kubeflow Pipelines ${KFP_VERSION}"

# Kubeflow Pipelines bundles its own MinIO (Deployment "minio", its PVC and
# Service). The platform provides object storage, and KFP's upstream image
# (gcr.io/ml-pipeline/minio:RELEASE.2019-08-14…) has been deleted from gcr.io,
# so those pods can never start. Strip them; manifests/platform-minio.yaml
# re-creates `minio-service` as an ExternalName alias to the platform MinIO and
# fills KFP's credential Secret from it.
python3 - "${INSTALL_YAML}" <<'PYEOF_INNER'
import sys, yaml
p = sys.argv[1]
docs = [d for d in yaml.safe_load_all(open(p)) if d]
kept = []
for d in docs:
    name = (d.get("metadata") or {}).get("name")
    kind = d.get("kind")
    if kind == "Deployment" and name == "minio": continue
    if kind == "PersistentVolumeClaim" and name == "minio-pvc": continue
    if kind == "Service" and name == "minio-service": continue
    kept.append(d)
with open(p, "w") as f:
    f.write("\n---\n".join(yaml.safe_dump(d, sort_keys=False) for d in kept))
print(f"stripped bundled MinIO: {len(docs) - len(kept)} resource(s)")
PYEOF_INNER

# KFP's api-server config resolves the object store from the MINIO_SERVICE_SERVICE_HOST /
# _PORT service-link env vars, which Kubernetes injects only for ClusterIP Services — never
# for the ExternalName alias platform-minio.yaml provides. Set them explicitly on every
# Deployment that consumes the object store.
python3 - "${INSTALL_YAML}" <<'PYEOF_MINIO'
import sys, yaml
p = sys.argv[1]
docs = [d for d in yaml.safe_load_all(open(p)) if d]
inject = [{"name": "MINIO_SERVICE_SERVICE_HOST", "value": "minio.adhar-system.svc.cluster.local"},
          {"name": "MINIO_SERVICE_SERVICE_PORT", "value": "9000"}]
n = 0
for d in docs:
    if d.get("kind") != "Deployment": continue
    for c in d["spec"]["template"]["spec"].get("containers", []):
        env = c.setdefault("env", [])
        names = {e.get("name") for e in env}
        blob = yaml.safe_dump(c)
        if "MINIO" in blob or "OBJECTSTORE" in blob or "minio" in blob or d["metadata"]["name"] in ("ml-pipeline", "ml-pipeline-persistenceagent", "ml-pipeline-ui", "ml-pipeline-scheduledworkflow", "ml-pipeline-viewer-crd", "metadata-writer"):
            for e in inject:
                if e["name"] not in names:
                    env.append(e); n += 1
with open(p, "w") as f:
    f.write("\n---\n".join(yaml.safe_dump(d, sort_keys=False) for d in docs))
print(f"injected MinIO service-link env into {n} container env lists")
PYEOF_MINIO
