#!/usr/bin/env bash
set -euo pipefail
# Kubeflow Pipelines (standalone) — the core ML pipeline orchestration component
# of Kubeflow. Full Kubeflow (notebooks/katib/kserve/central-dashboard) requires
# Istio + Dex + cert-manager and is far heavier than a single Kind node; the
# standalone Pipelines deployment ("platform-agnostic" env) is the portable,
# self-contained core and is what this package ships. Deploys into its own
# `kubeflow` namespace (the standalone manifests hard-code it).
#
# Bump KFP_VERSION and re-run to update. Requires kustomize (git-capable).
KFP_VERSION="${KFP_VERSION:-2.4.1}"
INSTALL_YAML="$(cd "$(dirname "$0")" && pwd)/manifests/install.yaml"
BASE="github.com/kubeflow/pipelines/manifests/kustomize"

mkdir -p "$(dirname "${INSTALL_YAML}")"
echo "# KUBEFLOW PIPELINES (standalone) INSTALL RESOURCES" >"${INSTALL_YAML}"
echo "# Auto-generated by platform/stack/packages/data/kubeflow/generate-manifests.sh" >>"${INSTALL_YAML}"
echo "# Source: kubeflow/pipelines ${KFP_VERSION} (env/platform-agnostic)" >>"${INSTALL_YAML}"

kustomize build "${BASE}/cluster-scoped-resources?ref=${KFP_VERSION}&timeout=120" >>"${INSTALL_YAML}"
echo "---" >>"${INSTALL_YAML}"
kustomize build "${BASE}/env/platform-agnostic?ref=${KFP_VERSION}&timeout=120" >>"${INSTALL_YAML}"

echo "Generated ${INSTALL_YAML} for Kubeflow Pipelines ${KFP_VERSION}"
