{
 "title": "Chaos Mesh | Chaos Daemon",
 "description": "Monitoring performance data provided by chaos-daemon, which is the powerful agent in Chaos Mesh.\r\n\r\nProviding metrics about networking and background-process-manager.",
 "tags": [
  "adhar",
  "application",
  "chaos-mesh"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Data source", "query": "prometheus" },
   {
    "name": "Namespace",
    "label": "Chaos Mesh Namespace",
    "query": {
     "query": "label_values(chaos_mesh_templates, namespace)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Networking", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "ipset",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "chaos_daemon_ipset_members{namespace=\"$Namespace\"}",
     "legendFormat": "{{exported_namespace}} {{exported_container}} "
    }
   ]
  },
  {
   "title": "netem tc",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "chaos_daemon_tcs{namespace=\"$Namespace\"}",
     "legendFormat": "{{exported_namespace}} {{exported_container}} "
    }
   ]
  },
  {
   "title": "iptables packets rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "rate(chaos_daemon_iptables_packets[$__rate_interval])"
    }
   ]
  },
  {
   "title": "iptables bytes rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(chaos_daemon_iptables_packet_bytes[$__rate_interval])"
    }
   ]
  },
  { "title": "Background Process Manager", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Current Controlled Processes",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "chaos_daemon_bpm_controlled_processes{namespace=\"$Namespace\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Processes Spawn Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 7, "x": 7, "y": 19 },
   "targets": [
    {
     "expr": "rate(chaos_daemon_bpm_controlled_process_total{namespace=\"$Namespace\"}[$__rate_interval])",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}