{
 "title": "Kyverno",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "kyvernoNS",
    "query": {
     "query": "label_values(kube_namespace_status_phase{job=\"kube-state-metrics\",}, namespace)"
    }
   },
   { "name": "DS_PROMETHEUS", "label": "Datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "# Kyverno\nA Kubernetes-native policy management engine\n\n#### About this dashboard\n\nThis dashboard represents generic insights which can be extracted and made well use of from a cluster with Kyverno in action.\n\n#### For more details around the metrics\n\nCheckout the [official docs of Kyverno metrics](https://kyverno.io/docs/monitoring-kyverno-with-prometheus-metrics/)"
   }
  },
  { "title": "Latest Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Rule Execution Success Rate",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kyverno_policy_results_total{rule_result=\"pass\"})*100/sum(kyverno_policy_results_total{})"
    }
   ]
  },
  {
   "title": "Cluster Policies",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(kyverno_policy_rule_info_total{policy_type=\"cluster\"}==1) by (policy_name))"
    }
   ]
  },
  {
   "title": "Policies",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(kyverno_policy_rule_info_total{policy_type=\"namespaced\"}==1) by (policy_name))"
    }
   ]
  },
  {
   "title": "Background Scans Success Rate",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kyverno_policy_results_total{rule_result=\"pass\", policy_background_mode=\"true\"})*100/sum(kyverno_policy_results_total{policy_background_mode=\"true\"})"
    }
   ]
  },
  {
   "title": "Validate Rules",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 6, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kyverno_policy_rule_info_total{rule_type=\"validate\"}==1)"
    }
   ]
  },
  {
   "title": "Mutate Rules",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 10, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kyverno_policy_rule_info_total{rule_type=\"mutate\"}==1)"
    }
   ]
  },
  {
   "title": "Generate Rules",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 14, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kyverno_policy_rule_info_total{rule_type=\"generate\"}==1)"
    }
   ]
  },
  {
   "title": "CPU Utilisation (from requests)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 3, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=\"$kyvernoNS\"}) / sum(kube_pod_container_resource_requests{job=\"kube-state-metrics\", namespace=\"$kyvernoNS\", resource=\"cpu\"})"
    }
   ]
  },
  {
   "title": "CPU Utilisation (from limits)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 7, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=\"$kyvernoNS\"}) / sum(kube_pod_container_resource_limits{job=\"kube-state-metrics\", namespace=\"$kyvernoNS\", resource=\"cpu\"})"
    }
   ]
  },
  {
   "title": "Memory Utilisation (from requests)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 11, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", namespace=\"$kyvernoNS\",container!=\"\", image!=\"\"}) / sum(kube_pod_container_resource_requests{job=\"kube-state-metrics\", namespace=\"$kyvernoNS\", resource=\"memory\"})"
    }
   ]
  },
  {
   "title": "Memory Utilisation (from limits)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 15, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", namespace=\"$kyvernoNS\",container!=\"\", image!=\"\"}) / sum(kube_pod_container_resource_limits{job=\"kube-state-metrics\", namespace=\"$kyvernoNS\", resource=\"memory\"})"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=\"$kyvernoNS\"}) by (pod)",
     "legendFormat": "{{ pod }}"
    },
    {
     "expr": "scalar(kube_resourcequota{namespace=\"$kyvernoNS\", type=\"hard\",resource=\"requests.cpu\"})",
     "legendFormat": "quota - requests"
    },
    {
     "expr": "scalar(kube_resourcequota{namespace=\"$kyvernoNS\", type=\"hard\",resource=\"limits.cpu\"})",
     "legendFormat": "quota - limits"
    }
   ]
  },
  {
   "title": "Memory Usage (w/o cache)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", namespace=\"$kyvernoNS\", container!=\"\", image!=\"\"}) by (pod)",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "scalar(kube_resourcequota{namespace=\"$kyvernoNS\", type=\"hard\",resource=\"requests.memory\"})",
     "legendFormat": "quota - requests"
    },
    {
     "expr": "scalar(kube_resourcequota{namespace=\"$kyvernoNS\", type=\"hard\",resource=\"limits.memory\"})",
     "legendFormat": "quota - limits"
    }
   ]
  },
  { "title": "Policy-Rule Results", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Admission Review Results (per-rule)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kyverno_policy_results_total{rule_execution_cause=\"admission_request\"}) by (rule_result)",
     "legendFormat": "{{rule_result}}"
    }
   ]
  },
  {
   "title": "Background Scan Results (per-rule)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kyverno_policy_results_total{rule_execution_cause=\"background_scan\"}) by (rule_result)",
     "legendFormat": "{{rule_result}}"
    }
   ]
  },
  {
   "title": "Policy Failures",
   "type": "graph",
   "gridPos": { "h": 16, "w": 8, "x": 16, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(sum(kyverno_policy_results_total{rule_result=\"fail\"}) by (policy_name, policy_type)) by (policy_type)",
     "legendFormat": "{{policy_type}}"
    }
   ]
  },
  {
   "title": "Admission Review Results (per-policy)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(sum(kyverno_policy_results_total{rule_execution_cause=\"admission_request\"}) by (policy_name, rule_result)) by (rule_result)",
     "legendFormat": "{{rule_result}}"
    }
   ]
  },
  {
   "title": "Background Scan Results (per-policy)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(sum(kyverno_policy_results_total{rule_execution_cause=\"background_scan\"}) by (policy_name, rule_result)) by (rule_result)",
     "legendFormat": "{{rule_result}}"
    }
   ]
  },
  {
   "title": "Cluster Policies and Namespaces w/Failed",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 42 },
   "targets": [
    {
     "expr": "count(kyverno_policy_results_total{rule_result=\"fail\"}) by (resource_namespace,policy_name)",
     "legendFormat": "Policy={{ policy_name }}, Namespace={{ resource_namespace }}"
    }
   ]
  },
  { "title": "Policy-Rule Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 } },
  {
   "title": "Active Policies (by policy type)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(count(kyverno_policy_rule_info_total{}==1) by (policy_name, policy_type)) by (policy_type)",
     "legendFormat": "{{policy_type}}"
    }
   ]
  },
  {
   "title": "Active Policies (by policy validation action)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 49 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(count(kyverno_policy_rule_info_total{}==1) by (policy_name, policy_validation_mode)) by (policy_validation_mode)",
     "legendFormat": "audit"
    }
   ]
  },
  {
   "title": "Active Policies running in background mode",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 49 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(count(kyverno_policy_rule_info_total{policy_background_mode=\"true\"}==1) by (policy_name, policy_type)) by (policy_type)",
     "legendFormat": "{{policy_type}}"
    }
   ]
  },
  {
   "title": "Active Namespaced Policies (by namespaces)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 57 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(count(kyverno_policy_rule_info_total{policy_namespace!=\"-\"}==1) by (policy_name, policy_namespace)) by (policy_namespace)",
     "legendFormat": "{{policy_namespace}}"
    }
   ]
  },
  {
   "title": "Active Rules (by rule type)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 8, "y": 57 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(kyverno_policy_rule_info_total{}==1) by (rule_type)",
     "legendFormat": "{{rule_type}}"
    }
   ]
  },
  { "title": "Policy-Rule Execution Latency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 65 } },
  {
   "title": "Average Rule Execution Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 66 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(kyverno_policy_execution_duration_seconds_sum{}) by (rule_type)",
     "legendFormat": "{{rule_type}}"
    }
   ]
  },
  {
   "title": "Average Policy Execution Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 9, "y": 66 },
   "yaxes": [
    { "format": "clocks" }
   ],
   "targets": [
    {
     "expr": "avg(sum(kyverno_policy_execution_duration_seconds_sum{}) by (policy_name, policy_type)) by (policy_type)",
     "legendFormat": "{{policy_type}}"
    }
   ]
  },
  {
   "title": "Overall Average Rule Execution Latency",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(kyverno_policy_execution_duration_seconds_sum{})"
    }
   ]
  },
  {
   "title": "Overall Average Policy Execution Latency",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(sum(kyverno_policy_execution_duration_seconds_sum{}) by (policy_name, policy_type))"
    }
   ]
  },
  { "title": "Admission Review Latency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 74 } },
  {
   "title": "Avg - Admission Review Duration (by operation)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 75 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(kyverno_admission_requests_total{}) by (resource_request_operation)",
     "legendFormat": "Resource Operation: {{resource_request_operation}}"
    }
   ]
  },
  {
   "title": "Avg - Admission Review Duration (by resource kind)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 9, "y": 75 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(kyverno_admission_requests_total{}) by (resource_kind)",
     "legendFormat": "Resource Kind: {{resource_kind}}"
    }
   ]
  },
  {
   "title": "Rate - Incoming Admission Requests (last 5m)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(kyverno_admission_requests_total{}[5m]))"
    }
   ]
  },
  {
   "title": "Avg - Overall Admission Review Duration",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(kyverno_admission_review_duration_seconds_sum{})"
    }
   ]
  },
  { "title": "Policy Changes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 83 } },
  {
   "title": "Policy Changes (by change type)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 84 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kyverno_policy_changes_total{}) by (policy_change_type)",
     "legendFormat": "Change type: {{policy_change_type}}"
    }
   ]
  },
  {
   "title": "Policy Changes (by policy type)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 9, "y": 84 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kyverno_policy_changes_total{}) by (policy_type)",
     "legendFormat": "{{policy_type}}"
    }
   ]
  },
  {
   "title": "Total Policy Changes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kyverno_policy_changes_total{})"
    }
   ]
  },
  {
   "title": "Rate - Policy Changes Happening (last 5m)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 88 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(kyverno_admission_requests_total{}[5m]))"
    }
   ]
  },
  { "title": "Admission Requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 92 } },
  {
   "title": "Admission Requests (by operation)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 93 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kyverno_admission_requests_total{}) by (resource_request_operation)",
     "legendFormat": "Resource Operation: {{resource_request_operation}}"
    }
   ]
  },
  {
   "title": "Admission Requests (by resource kind)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 9, "y": 93 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kyverno_admission_requests_total{}) by (resource_kind)",
     "legendFormat": "Resource Kind: {{resource_kind}}"
    }
   ]
  },
  {
   "title": "Total Admission Requests",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 93 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kyverno_admission_requests_total{})"
    }
   ]
  }
 ]
}