{
 "title": "harbor",
 "tags": [ "harbor" ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "实例",
    "query": {
     "query": "label_values(harbor_health,instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Data Panel", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Harbor Up Nums",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "sum(harbor_health)" }
   ]
  },
  {
   "title": "Portal Up Nums",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(harbor_up{component=\"portal\"})"
    }
   ]
  },
  {
   "title": "Core Up Nums",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(harbor_up{component=\"core\"})"
    }
   ]
  },
  {
   "title": "Registry Up Nums",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(harbor_up{component=\"registry\"})"
    }
   ]
  },
  {
   "title": "Registryctl Up Nums",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(harbor_up{component=\"registryctl\"})"
    }
   ]
  },
  {
   "title": "Redis Up Nums",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(harbor_up{component=\"redis\"})"
    }
   ]
  },
  {
   "title": "Database Up Nums",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(harbor_up{component=\"database\"})"
    }
   ]
  },
  {
   "title": "Jobservice Up Nums",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(harbor_up{component=\"jobservice\"})"
    }
   ]
  },
  {
   "title": "Storage Use",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(harbor_project_quota_usage_byte{instance=~\"$instance\"}) / sum(harbor_health{instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Tag Nums",
   "type": "stat",
   "gridPos": { "h": 7, "w": 7, "x": 6, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(harbor_project_artifact_total{instance=~\"$instance\"}) / sum(harbor_health{instance=~\"$instance\"})"
    }
   ]
  },
  { "title": "Core Panel", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Project Image Pull Rate (1min)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(sum(harbor_artifact_pulled{instance=~\"$instance\"}) by (project_name)) - (sum(harbor_artifact_pulled{instance=~\"$instance\"} offset 1m) by (project_name))",
     "legendFormat": "{{ project_name }}"
    }
   ]
  },
  {
   "title": "Core Request Rate By Operation",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(sum(harbor_core_http_request_total{instance=~\"$instance\"}) by (method,operation)) - sum(harbor_core_http_request_total{instance=~\"$instance\"} offset 1m) by (method,operation)",
     "legendFormat": "{{method}} : {{operation}}"
    }
   ]
  },
  {
   "title": "Core Request Latency By Operation (P99,Second)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(harbor_core_http_request_duration_seconds{instance=~\"$instance\",quantile=\"0.99\"}) by (method,operation)",
     "legendFormat": "{{method}} : {{operation}}"
    }
   ]
  },
  {
   "title": "Project Image Newly Rate  Weekly",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(sum(harbor_project_artifact_total{instance=~\"$instance\",artifact_type=\"IMAGE\"}) by (project_name)) - sum(harbor_project_artifact_total{instance=~\"$instance\",artifact_type=\"IMAGE\"} offset 7d) by (project_name)",
     "legendFormat": "{{project_name}}"
    }
   ]
  },
  {
   "title": "Storage Use Increase Weekly",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(sum(harbor_project_quota_usage_byte{instance=~\"$instance\"}) by (project_name)) - sum(harbor_project_quota_usage_byte{instance=~\"$instance\"} offset 7d) by (project_name)",
     "legendFormat": "{{project_name}}"
    }
   ]
  },
  { "title": "Registry Panel", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "Registry Request Rate By Handler(Minute)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(sum(registry_http_requests_total{instance=~\"$instance\"}) by (method,handler)) - sum(registry_http_requests_total{instance=~\"$instance\"} offset 1m) by (method,handler)",
     "legendFormat": "{{method}} : {{handler}}"
    }
   ]
  },
  {
   "title": "Registry Request By Latency Handler (P99,Second)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 39 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(registry_http_request_duration_seconds_bucket{instance=~\"$instance\"}[1m]))by(method,handler,le))",
     "legendFormat": "{{method}} : {{handler}}"
    }
   ]
  },
  {
   "title": "Registry Request Bytes (P99)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 47 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(registry_http_request_size_bytes_bucket[1m])) by (handler,le) ) ",
     "legendFormat": "{{handler}} "
    }
   ]
  },
  {
   "title": "Registry Response Bytes (P99)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 47 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(registry_http_response_size_bytes_bucket[1m])) by (handler,le))",
     "legendFormat": "{{handler}}"
    }
   ]
  },
  {
   "title": "Registry Storage Cache Use Rate (Second)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 55 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(registry_storage_cache_total{instance=~\"$instance\"}) by (type) - sum(registry_storage_cache_total{instance=~\"$instance\"} offset 1m) by (type)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Registry Storage Action Seconds (P99)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 55 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(registry_storage_action_seconds_bucket[1m]))by(action,driver,le))",
     "legendFormat": "{{action}} : {{driver}}"
    }
   ]
  },
  { "title": "System Panel", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 63 } },
  {
   "title": "Instance Memory Use",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(go_memstats_alloc_bytes{instance=~\"$instance\"}) by (instance)",
     "legendFormat": "{{ instance }} "
    }
   ]
  },
  {
   "title": "Open fd",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 64 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(process_open_fds{instance=~\"$instance\"}) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Gorouting Nums",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 72 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(go_goroutines{instance=~\"$instance\"}) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}