{
 "title": "Kubernetes / Autoscaling / KEDA / Scaled Object",
 "description": "A dashboard that monitors KEDA Scaled Objects. The dashboards were generated using [kubernetes-autoscaling-mixin](https://github.com/adinhodovic/kubernetes-autoscaling-mixin). Open issues and create feature requests in the repository.",
 "tags": [
  "kubernetes",
  "autoscaling",
  "kubernetes-autoscaling-mixin",
  "keda"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "label_values(keda_build_info{}, cluster)"
   },
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(keda_scaled_object_paused{cluster=\"$cluster\"}, job)"
   },
   {
    "name": "operator_namespace",
    "label": "Operator Namespace",
    "query": "label_values(keda_scaled_object_paused{cluster=\"$cluster\", job=~\"$job\"}, namespace)"
   },
   {
    "name": "resource_namespace",
    "label": "Resource Namespace",
    "query": "label_values(keda_scaled_object_paused{cluster=\"$cluster\", job=~\"$job\", namespace=~\"$operator_namespace\"}, exported_namespace)"
   },
   {
    "name": "scaled_object",
    "label": "Scaled Object",
    "query": "label_values(keda_scaled_object_paused{cluster=\"$cluster\", job=~\"$job\", namespace=~\"$operator_namespace\", exported_namespace=~\"$resource_namespace\"}, scaledObject)"
   },
   {
    "name": "scaler",
    "label": "Scaler",
    "query": "label_values(keda_scaler_active{cluster=\"$cluster\", job=~\"$job\", namespace=~\"$operator_namespace\", exported_namespace=\"$resource_namespace\", type=\"scaledobject\", scaledObject=\"$scaled_object\"}, scaler)"
   },
   {
    "name": "metric",
    "label": "Metric",
    "query": "label_values(keda_scaler_active{cluster=\"$cluster\", job=~\"$job\", namespace=~\"$operator_namespace\", exported_namespace=\"$resource_namespace\", type=\"scaledobject\", scaledObject=\"$scaled_object\", scaler=\"$scaler\"}, metric)"
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Resources Registered by Namespace",
   "type": "timeseries",
   "description": "The number of scaled object resources registered by namespace.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(\n  keda_resource_registered_total{\n    cluster=\"$cluster\",\njob=~\"$job\",\nnamespace=~\"$operator_namespace\"\n,\n    type=\"scaled_object\"\n  }\n) by (exported_namespace, type)\n",
     "legendFormat": "{{ exported_namespace}} / {{ type }}"
    }
   ]
  },
  {
   "title": "Triggers by Type",
   "type": "timeseries",
   "description": "The number of triggers registered by type.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(\n  keda_trigger_registered_total{\n    cluster=\"$cluster\",\njob=~\"$job\",\nnamespace=~\"$operator_namespace\"\n\n  }\n) by (type)\n",
     "legendFormat": "{{ type }}"
    }
   ]
  },
  {
   "title": "Scaled Objects Errors",
   "type": "timeseries",
   "description": "The rate of errors for scaled objects.",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(\n  increase(\n    keda_scaled_object_errors_total{\n      cluster=\"$cluster\",\njob=~\"$job\",\nnamespace=~\"$operator_namespace\"\n,\nexported_namespace=~\"$resource_namespace\"\n\n    }[$__rate_interval]\n  )\n) by (exported_namespace, scaledObject)\n",
     "legendFormat": "{{ scaledObject }}"
    }
   ]
  },
  {
   "title": "Scaler Detail Errors",
   "type": "timeseries",
   "description": "The rate of scaler detail errors.",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(\n  increase(\n    keda_scaler_detail_errors_total{\n      cluster=\"$cluster\",\njob=~\"$job\",\nnamespace=~\"$operator_namespace\"\n,\nexported_namespace=~\"$resource_namespace\"\n,\n      type=\"scaledobject\"\n    }[$__rate_interval]\n  )\n) by (exported_namespace, scaledObject, scaler)\n",
     "legendFormat": "{{ scaledObject }} / {{ scaler }}"
    }
   ]
  },
  {
   "title": "Scaled Objects Paused",
   "type": "timeseries",
   "description": "Scaled objects that are currently paused.",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(\n  keda_scaled_object_paused{\n    cluster=\"$cluster\",\njob=~\"$job\",\nnamespace=~\"$operator_namespace\"\n,\nexported_namespace=~\"$resource_namespace\"\n\n  }\n) by (exported_namespace, scaledObject)\n> 0\n",
     "legendFormat": "{{ scaledObject }}"
    }
   ]
  },
  {
   "title": "Scale Target Values",
   "type": "table",
   "description": "This table has links to the HPA for the scaled object, which can be used to see the current scaling status and history. The HPA dashboard can be found at [kubernetes-autoscaling-mixin](https://github.com/adinhodovic/kubernetes-autoscaling-mixin).",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(\n  keda_scaler_metrics_value{\n    cluster=\"$cluster\",\njob=~\"$job\",\nnamespace=~\"$operator_namespace\"\n,\nexported_namespace=~\"$resource_namespace\"\n,\n    type=\"scaledobject\"\n  }\n) by (cluster, job, exported_namespace, scaledObject, scaler, metric)\n"
    }
   ]
  },
  {
   "title": "Scaled Object $scaled_object / $scaler / $metric",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 }
  },
  {
   "title": "Scaled Object Paused",
   "type": "timeseries",
   "description": "Whether the selected scaled object is paused.",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(\n  keda_scaled_object_paused{\n    cluster=\"$cluster\",\njob=~\"$job\",\nnamespace=~\"$operator_namespace\"\n,\nexported_namespace=~\"$resource_namespace\"\n,\ntype=\"scaledobject\",\nscaledObject=\"$scaled_object\"\n\n  }\n) by (exported_namespace, scaledObject)\n",
     "legendFormat": "{{ scaledObject }}"
    }
   ]
  },
  {
   "title": "Scaled Object Active",
   "type": "timeseries",
   "description": "Whether the selected scaled object is active.",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(\n  keda_scaler_active{\n    cluster=\"$cluster\",\njob=~\"$job\",\nnamespace=~\"$operator_namespace\"\n,\nexported_namespace=~\"$resource_namespace\"\n,\ntype=\"scaledobject\",\nscaledObject=\"$scaled_object\"\n\n  }\n) by (exported_namespace, scaledObject)\n",
     "legendFormat": "{{ scaledObject }}"
    }
   ]
  },
  {
   "title": "Scaled Object Detail Errors",
   "type": "timeseries",
   "description": "The rate of errors for the selected scaled object.",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(\n  increase(\n    keda_scaler_detail_errors_total{\n      cluster=\"$cluster\",\njob=~\"$job\",\nnamespace=~\"$operator_namespace\"\n,\nexported_namespace=~\"$resource_namespace\"\n,\ntype=\"scaledobject\",\nscaledObject=\"$scaled_object\"\n\n    }[$__rate_interval]\n  )\n) by (exported_namespace, scaledObject)\n",
     "legendFormat": "{{ scaledObject }}"
    }
   ]
  },
  {
   "title": "Scaled Object Metric Value",
   "type": "timeseries",
   "description": "The metric value for the selected scaled object.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg(\n  keda_scaler_metrics_value{\n    cluster=\"$cluster\",\njob=~\"$job\",\nnamespace=~\"$operator_namespace\"\n,\nexported_namespace=~\"$resource_namespace\"\n,\ntype=\"scaledobject\",\nscaledObject=\"$scaled_object\"\n,\nscaler=\"$scaler\"\n,\nmetric=\"$metric\"\n\n  }\n) by (exported_namespace, scaledObject, scaler, metric)\n",
     "legendFormat": "{{ scaledObject }} / {{ scaler }} / {{ metric }}"
    }
   ]
  },
  {
   "title": "Scaled Object Metric Latency",
   "type": "timeseries",
   "description": "The metric collection latency for the selected scaled object.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(\n  keda_scaler_metrics_latency_seconds{\n    cluster=\"$cluster\",\njob=~\"$job\",\nnamespace=~\"$operator_namespace\"\n,\nexported_namespace=~\"$resource_namespace\"\n,\ntype=\"scaledobject\",\nscaledObject=\"$scaled_object\"\n,\nscaler=\"$scaler\"\n,\nmetric=\"$metric\"\n\n  }\n) by (exported_namespace, scaledObject, scaler, metric)\n",
     "legendFormat": "{{ scaledObject }} / {{ scaler }} / {{ metric }}"
    }
   ]
  }
 ]
}