{
 "title": "Trino Cluster JMX",
 "description": "Trino deploy on k8s, collect jmx to monitor cluster",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "cluster",
    "query": {
     "query": "label_values(trino_execution_QueryManager_RunningQueries,app)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "集群状态概况",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "active worker数量",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "trino_failuredetector_HeartbeatFailureDetector_ActiveCount{app='${cluster}'}",
       "legendFormat": "{{app}}-今日"
      },
      {
       "expr": "trino_failuredetector_HeartbeatFailureDetector_ActiveCount{app='${cluster}'} offset 1d",
       "legendFormat": "{{app}}-昨日"
      },
      {
       "expr": "trino_failuredetector_HeartbeatFailureDetector_ActiveCount{app='${cluster}'} offset 7d",
       "legendFormat": "{{app}}-七日前"
      }
     ]
    },
    {
     "title": "blocked worker数量",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "trino_memory_ClusterMemoryPool_BlockedNodes{app=~\"${cluster}\"}",
       "legendFormat": "{{app}}-今日"
      },
      {
       "expr": "trino_memory_ClusterMemoryPool_BlockedNodes{app=~\"${cluster}\"} offset 1d",
       "legendFormat": "{{app}}-昨日"
      },
      {
       "expr": "trino_memory_ClusterMemoryPool_BlockedNodes{app=~\"${cluster}\"} offset 7d",
       "legendFormat": "{{app}}-7日前"
      }
     ]
    },
    {
     "title": "CPU总核数",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "trino_memory_ClusterMemoryManager_TotalAvailableProcessors{app=~\"${cluster}\"}",
       "legendFormat": "{{app}}-今日"
      },
      {
       "expr": "trino_memory_ClusterMemoryManager_TotalAvailableProcessors{app=~\"${cluster}\"} offset 1d",
       "legendFormat": "{{app}}-昨日"
      },
      {
       "expr": "trino_memory_ClusterMemoryManager_TotalAvailableProcessors{app=~\"${cluster}\"} offset 7d",
       "legendFormat": "{{app}}-七日前"
      }
     ]
    },
    {
     "title": "Total Distributed Bytes (cluster memory pool)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "trino_memory_ClusterMemoryPool_TotalDistributedBytes{app=~\"${cluster}\"}",
       "legendFormat": "{{app}}-今日"
      },
      {
       "expr": "trino_memory_ClusterMemoryPool_TotalDistributedBytes{app=~\"${cluster}\"} offset 1d",
       "legendFormat": "{{app}}-昨日"
      },
      {
       "expr": "trino_memory_ClusterMemoryPool_TotalDistributedBytes{app=~\"${cluster}\"} offset 7d",
       "legendFormat": "{{app}}-7日前"
      }
     ]
    },
    {
     "title": "Free Distributed Bytes (cluster memory pool)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "trino_memory_ClusterMemoryPool_FreeDistributedBytes{app=~\"${cluster}\"}",
       "legendFormat": "{{app}}-今日"
      },
      {
       "expr": "trino_memory_ClusterMemoryPool_FreeDistributedBytes{app=~\"${cluster}\"} offset 1d",
       "legendFormat": "{{app}}-昨日"
      },
      {
       "expr": "trino_memory_ClusterMemoryPool_FreeDistributedBytes{app=~\"${cluster}\"} offset 7d",
       "legendFormat": "{{app}}-7日前"
      }
     ]
    },
    {
     "title": "Reserved Revocable Distributed Bytes (cluster memory pool)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "trino_memory_ClusterMemoryPool_ReservedRevocableDistributedBytes{app=~\"${cluster}\"}",
       "legendFormat": "{{app}}-今日"
      },
      {
       "expr": "trino_memory_ClusterMemoryPool_ReservedRevocableDistributedBytes{app=~\"${cluster}\"} offset 1d",
       "legendFormat": "{{app}}-昨日"
      },
      {
       "expr": "trino_memory_ClusterMemoryPool_ReservedRevocableDistributedBytes{app=~\"${cluster}\"} offset 7d",
       "legendFormat": "{{app}}-7日前"
      }
     ]
    },
    {
     "title": "Reserved Distributed Bytes (cluster memory pool)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "trino_memory_ClusterMemoryPool_ReservedDistributedBytes{app=~\"${cluster}\"}",
       "legendFormat": "{{app}}-今日"
      },
      {
       "expr": "trino_memory_ClusterMemoryPool_ReservedDistributedBytes{app=~\"${cluster}\"} offset 1d",
       "legendFormat": "{{app}}-昨日"
      },
      {
       "expr": "trino_memory_ClusterMemoryPool_ReservedDistributedBytes{app=~\"${cluster}\"} offset 7d",
       "legendFormat": "{{app}}-7日前"
      }
     ]
    },
    {
     "title": "Cluster User Memory Reservation (Running查询使用总和)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "trino_memory_ClusterMemoryManager_ClusterUserMemoryReservation{app=~\"${cluster}\"}",
       "legendFormat": "{{app}}-今日"
      },
      {
       "expr": "trino_memory_ClusterMemoryManager_ClusterUserMemoryReservation{app=~\"${cluster}\"} offset 1d",
       "legendFormat": "{{app}}-昨日"
      },
      {
       "expr": "trino_memory_ClusterMemoryManager_ClusterUserMemoryReservation{app=~\"${cluster}\"} offset 7d",
       "legendFormat": "{{app}}-7日前"
      }
     ]
    },
    {
     "title": "Cluster Total Memory Reservation (Running查询使用总和)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "trino_memory_ClusterMemoryManager_ClusterTotalMemoryReservation{app=~\"${cluster}\"}",
       "legendFormat": "{{app}}-今日"
      },
      {
       "expr": "trino_memory_ClusterMemoryManager_ClusterTotalMemoryReservation{app=~\"${cluster}\"} offset 1d",
       "legendFormat": "{{app}}-昨日"
      },
      {
       "expr": "trino_memory_ClusterMemoryManager_ClusterTotalMemoryReservation{app=~\"${cluster}\"} offset 7d",
       "legendFormat": "{{app}}-7日前"
      }
     ]
    }
   ]
  },
  {
   "title": "查询执行概况",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Running查询数",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
     "targets": [
      {
       "expr": "trino_execution_QueryManager_RunningQueries{app=~\"${cluster}\"}",
       "legendFormat": "{{app}}-今日"
      },
      {
       "expr": "trino_execution_QueryManager_RunningQueries{app=~\"${cluster}\"} offset 1d",
       "legendFormat": "{{app}}-昨日"
      },
      {
       "expr": "trino_execution_QueryManager_RunningQueries{app=~\"${cluster}\"} offset 7d",
       "legendFormat": "{{app}}-七日前"
      }
     ]
    },
    {
     "title": "Queued查询数",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
     "targets": [
      {
       "expr": "trino_execution_QueryManager_QueuedQueries{app=~\"${cluster}\"}",
       "legendFormat": "{{app}}-今日"
      },
      {
       "expr": "trino_execution_QueryManager_QueuedQueries{app=~\"${cluster}\"} offset 1d",
       "legendFormat": "{{app}}-昨日"
      },
      {
       "expr": "trino_execution_QueryManager_QueuedQueries{app=~\"${cluster}\"} offset 7d",
       "legendFormat": "{{app}}-七日前"
      }
     ]
    },
    {
     "title": "每分钟查询提交数",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 10 },
     "targets": [
      {
       "expr": "increase(trino_execution_QueryManager_SubmittedQueries_TotalCount{app=~\"$cluster\"}[1m])",
       "legendFormat": "{{app}}-今日"
      },
      {
       "expr": "increase(trino_execution_QueryManager_SubmittedQueries_TotalCount{app=~\"$cluster\"}[1m] offset 1d)  ",
       "legendFormat": "{{app}}-昨日"
      },
      {
       "expr": "increase(trino_execution_QueryManager_SubmittedQueries_TotalCount{app=~\"$cluster\"}[1m] offset 7d) ",
       "legendFormat": "{{app}}-七日前"
      }
     ]
    },
    {
     "title": "每分钟查询完成数",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 10 },
     "targets": [
      {
       "expr": "increase(trino_execution_QueryManager_CompletedQueries_TotalCount{app=~\"$cluster\"}[1m])",
       "legendFormat": "{{app}}-今日"
      },
      {
       "expr": "increase(trino_execution_QueryManager_CompletedQueries_TotalCount{app=~\"$cluster\"}[1m] offset 1d)",
       "legendFormat": "{{app}}-昨日"
      },
      {
       "expr": "increase(trino_execution_QueryManager_CompletedQueries_TotalCount{app=~\"$cluster\"}[1m] offset 7d)",
       "legendFormat": "{{app}}-七日前"
      }
     ]
    },
    {
     "title": "每分钟查询失败数",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 10 },
     "targets": [
      {
       "expr": "increase(trino_execution_QueryManager_FailedQueries_TotalCount{app=~\"$cluster\"}[1m])",
       "legendFormat": "{{app}}-今日"
      },
      {
       "expr": "increase(trino_execution_QueryManager_FailedQueries_TotalCount{app=~\"$cluster\"}[1m] offset 1d)",
       "legendFormat": "{{app}}-昨日"
      },
      {
       "expr": "increase(trino_execution_QueryManager_FailedQueries_TotalCount{app=~\"$cluster\"}[1m] offset 7d)",
       "legendFormat": "{{app}}-七日前"
      }
     ]
    },
    {
     "title": "每分钟内存泄漏的查询总数",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
     "targets": [
      {
       "expr": "increase(trino_memory_ClusterMemoryManager_NumberOfLeakedQueries{app=~\"$cluster\"}[1m])",
       "legendFormat": "{{app}}-今日"
      },
      {
       "expr": "increase(trino_memory_ClusterMemoryManager_NumberOfLeakedQueries{app=~\"$cluster\"}[1m] offset 1d)",
       "legendFormat": "{{app}}-昨日"
      },
      {
       "expr": "increase(trino_memory_ClusterMemoryManager_NumberOfLeakedQueries{app=~\"$cluster\"}[1m] offset 7d)",
       "legendFormat": "{{app}}-七天前"
      }
     ]
    },
    {
     "title": "每分钟oom killed的查询总数",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
     "targets": [
      {
       "expr": "increase(trino_memory_ClusterMemoryManager_QueriesKilledDueToOutOfMemory{app=~\"$cluster\"}[1m])",
       "legendFormat": "{{app}}-今日"
      },
      {
       "expr": "increase(trino_memory_ClusterMemoryManager_QueriesKilledDueToOutOfMemory{app=~\"$cluster\"}[1m] offset 1d)",
       "legendFormat": "{{app}}-昨日"
      },
      {
       "expr": "increase(trino_memory_ClusterMemoryManager_QueriesKilledDueToOutOfMemory{app=~\"$cluster\"}[1m] offset 7d)",
       "legendFormat": "{{app}}-七日前"
      }
     ]
    }
   ]
  },
  {
   "title": "任务执行调度概况",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "最近一分钟Task(Finished)Cpu耗时平均值",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "trino_execution_scheduler_TaskExecutionStats_FinishedTasks_CpuTime_OneMinute_Avg{app=~\"${cluster}\"}",
       "legendFormat": "{{app}}-今日"
      },
      {
       "expr": "trino_execution_scheduler_TaskExecutionStats_FinishedTasks_CpuTime_OneMinute_Avg{app=~\"${cluster}\"} offset 1d",
       "legendFormat": "{{app}}-昨日"
      },
      {
       "expr": "trino_execution_scheduler_TaskExecutionStats_FinishedTasks_CpuTime_OneMinute_Avg{app=~\"${cluster}\"} offset 7d",
       "legendFormat": "{{app}}-7日前"
      }
     ]
    },
    {
     "title": "最近一分钟Task(Finished)Cpu耗时最大值",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "trino_execution_scheduler_TaskExecutionStats_FinishedTasks_CpuTime_OneMinute_Max{app=~\"${cluster}\"}",
       "legendFormat": "{{app}}-今日"
      },
      {
       "expr": "trino_execution_scheduler_TaskExecutionStats_FinishedTasks_CpuTime_OneMinute_Max{app=~\"${cluster}\"} offset 1d",
       "legendFormat": "{{app}}-昨日"
      },
      {
       "expr": "trino_execution_scheduler_TaskExecutionStats_FinishedTasks_CpuTime_OneMinute_Max{app=~\"${cluster}\"} offset 7d",
       "legendFormat": "{{app}}-7日前"
      }
     ]
    },
    {
     "title": "最近一分钟Task(Finished)执行耗时平均值",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "trino_execution_scheduler_TaskExecutionStats_FinishedTasks_ElapsedTime_OneMinute_Avg{app=~\"${cluster}\"}",
       "legendFormat": "{{app}}-今日"
      },
      {
       "expr": "trino_execution_scheduler_TaskExecutionStats_FinishedTasks_ElapsedTime_OneMinute_Avg{app=~\"${cluster}\"} offset 1d",
       "legendFormat": "{{app}}-昨日"
      },
      {
       "expr": "trino_execution_scheduler_TaskExecutionStats_FinishedTasks_ElapsedTime_OneMinute_Avg{app=~\"${cluster}\"} offset 7d",
       "legendFormat": "{{app}}-7日前"
      }
     ]
    },
    {
     "title": "最近一分钟Task(Finished)执行耗时最大值",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "trino_execution_scheduler_TaskExecutionStats_FinishedTasks_ElapsedTime_OneMinute_Max{app=~\"${cluster}\"}",
       "legendFormat": "{{app}}-今日"
      },
      {
       "expr": "trino_execution_scheduler_TaskExecutionStats_FinishedTasks_ElapsedTime_OneMinute_Max{app=~\"${cluster}\"} offset 1d",
       "legendFormat": "{{app}}-昨日"
      },
      {
       "expr": "trino_execution_scheduler_TaskExecutionStats_FinishedTasks_ElapsedTime_OneMinute_Max{app=~\"${cluster}\"} offset 7d",
       "legendFormat": "{{app}}-7日前"
      }
     ]
    },
    {
     "title": "最近一分钟Task(Finished)InputBlockedTime平均值",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "trino_execution_scheduler_TaskExecutionStats_FinishedTasks_InputBlockedTime_OneMinute_Avg{app=~\"${cluster}\"}",
       "legendFormat": "{{app}}-今日"
      },
      {
       "expr": "trino_execution_scheduler_TaskExecutionStats_FinishedTasks_InputBlockedTime_OneMinute_Avg{app=~\"${cluster}\"} offset 1d",
       "legendFormat": "{{app}}-昨日"
      },
      {
       "expr": "trino_execution_scheduler_TaskExecutionStats_FinishedTasks_InputBlockedTime_OneMinute_Avg{app=~\"${cluster}\"} offset 7d",
       "legendFormat": "{{app}}-7日前"
      }
     ]
    },
    {
     "title": "最近一分钟Task(Finished)InputBlockedTime最大值",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "trino_execution_scheduler_TaskExecutionStats_FinishedTasks_InputBlockedTime_OneMinute_Max{app=~\"${cluster}\"}",
       "legendFormat": "{{app}}-今日"
      },
      {
       "expr": "trino_execution_scheduler_TaskExecutionStats_FinishedTasks_InputBlockedTime_OneMinute_Max{app=~\"${cluster}\"} offset 1d",
       "legendFormat": "{{app}}-昨日"
      },
      {
       "expr": "trino_execution_scheduler_TaskExecutionStats_FinishedTasks_InputBlockedTime_OneMinute_Max{app=~\"${cluster}\"} offset 7d",
       "legendFormat": "{{app}}-7日前"
      }
     ]
    },
    {
     "title": "最近一分钟Task(Finished)OutputBlockedTime平均值",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "trino_execution_scheduler_TaskExecutionStats_FinishedTasks_OutputBlockedTime_OneMinute_Avg{app=~\"${cluster}\"}",
       "legendFormat": "{{app}}-今日"
      },
      {
       "expr": "trino_execution_scheduler_TaskExecutionStats_FinishedTasks_OutputBlockedTime_OneMinute_Avg{app=~\"${cluster}\"} offset 1d",
       "legendFormat": "{{app}}-昨日"
      },
      {
       "expr": "trino_execution_scheduler_TaskExecutionStats_FinishedTasks_OutputBlockedTime_OneMinute_Avg{app=~\"${cluster}\"} offset 7d",
       "legendFormat": "{{app}}-7日前"
      }
     ]
    },
    {
     "title": "最近一分钟Task(Finished)OutputBlockedTime最大值",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "trino_execution_scheduler_TaskExecutionStats_FinishedTasks_OutputBlockedTime_OneMinute_Max{app=~\"${cluster}\"}",
       "legendFormat": "{{app}}-今日"
      },
      {
       "expr": "trino_execution_scheduler_TaskExecutionStats_FinishedTasks_OutputBlockedTime_OneMinute_Max{app=~\"${cluster}\"} offset 1d",
       "legendFormat": "{{app}}-昨日"
      },
      {
       "expr": "trino_execution_scheduler_TaskExecutionStats_FinishedTasks_OutputBlockedTime_OneMinute_Max{app=~\"${cluster}\"} offset 7d",
       "legendFormat": "{{app}}-7日前"
      }
     ]
    },
    {
     "title": "最近一分钟Task(Finished)PeakMemoryReservation平均值",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "trino_execution_scheduler_TaskExecutionStats_FinishedTasks_PeakMemoryReservationInBytes_OneMinute_Avg{app=~\"${cluster}\"}",
       "legendFormat": "{{app}}-今日"
      },
      {
       "expr": "trino_execution_scheduler_TaskExecutionStats_FinishedTasks_PeakMemoryReservationInBytes_OneMinute_Avg{app=~\"${cluster}\"} offset 1d",
       "legendFormat": "{{app}}-昨日"
      },
      {
       "expr": "trino_execution_scheduler_TaskExecutionStats_FinishedTasks_PeakMemoryReservationInBytes_OneMinute_Avg{app=~\"${cluster}\"} offset 7d",
       "legendFormat": "{{app}}-7日前"
      }
     ]
    },
    {
     "title": "最近一分钟Task(Finished)PeakMemoryReservation最大值",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "trino_execution_scheduler_TaskExecutionStats_FinishedTasks_PeakMemoryReservationInBytes_OneMinute_Max{app=~\"${cluster}\"}",
       "legendFormat": "{{app}}-今日"
      },
      {
       "expr": "trino_execution_scheduler_TaskExecutionStats_FinishedTasks_PeakMemoryReservationInBytes_OneMinute_Max{app=~\"${cluster}\"} offset 1d",
       "legendFormat": "{{app}}-昨日"
      },
      {
       "expr": "trino_execution_scheduler_TaskExecutionStats_FinishedTasks_PeakMemoryReservationInBytes_OneMinute_Max{app=~\"${cluster}\"} offset 7d",
       "legendFormat": "{{app}}-7日前"
      }
     ]
    },
    {
     "title": "Task Descriptor Storage  Reserved Bytes",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "trino_execution_scheduler_TaskDescriptorStorage_ReservedBytes{app=~\"${cluster}\"}",
       "legendFormat": "{{app}}-今日"
      },
      {
       "expr": "trino_execution_scheduler_TaskDescriptorStorage_ReservedBytes{app=~\"${cluster}\"} offset 1d",
       "legendFormat": "{{app}}-昨日"
      },
      {
       "expr": "trino_execution_scheduler_TaskDescriptorStorage_ReservedBytes{app=~\"${cluster}\"} offset 7d",
       "legendFormat": "{{app}}-7日前"
      }
     ]
    }
   ]
  },
  {
   "title": "最近完成Query数据处理概况",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "近一分钟完成Query处理字节数累计值",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "increase(trino_execution_QueryManager_ConsumedInputBytes_TotalCount{app=~\"$cluster\"}[1m])",
       "legendFormat": "{{app}}-今日"
      },
      {
       "expr": "increase(trino_execution_QueryManager_ConsumedInputBytes_TotalCount{app=~\"$cluster\"}[1m] offset 1d)",
       "legendFormat": "{{app}}-昨日"
      },
      {
       "expr": "increase(trino_execution_QueryManager_ConsumedInputBytes_TotalCount{app=~\"$cluster\"}[1m] offset 7d)",
       "legendFormat": "{{app}}-七日前"
      }
     ]
    },
    {
     "title": "近一分钟完成QueryCPU耗时累计值",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "increase(trino_execution_QueryManager_ConsumedCpuTimeSecs_TotalCount{app=~\"$cluster\"}[1m])",
       "legendFormat": "{{app}}-今日"
      },
      {
       "expr": "increase(trino_execution_QueryManager_ConsumedCpuTimeSecs_TotalCount{app=~\"$cluster\"}[1m] offset 1d)",
       "legendFormat": "{{app}}-昨日"
      },
      {
       "expr": "increase(trino_execution_QueryManager_ConsumedCpuTimeSecs_TotalCount{app=~\"$cluster\"}[1m] offset 7d)",
       "legendFormat": "{{app}}-七日前"
      }
     ]
    },
    {
     "title": "近一分钟完成Query数据处理平均速率",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "trino_execution_QueryManager_WallInputBytesRate_OneMinute_Avg{app=~\"$cluster\"}",
       "legendFormat": "{{app}}-今日"
      },
      {
       "expr": "trino_execution_QueryManager_WallInputBytesRate_OneMinute_Avg{app=~\"$cluster\"} offset 1d",
       "legendFormat": "{{app}}-昨日"
      },
      {
       "expr": "trino_execution_QueryManager_WallInputBytesRate_OneMinute_Avg{app=~\"$cluster\"} offset 7d",
       "legendFormat": "{{app}}-七日前"
      }
     ]
    },
    {
     "title": "近一分钟完成Query数据处理最大速率",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "trino_execution_QueryManager_WallInputBytesRate_OneMinute_Max{app=~\"$cluster\"}",
       "legendFormat": "{{app}}-今日"
      },
      {
       "expr": "trino_execution_QueryManager_WallInputBytesRate_OneMinute_Max{app=~\"$cluster\"} offset 1d",
       "legendFormat": "{{app}}-昨日"
      },
      {
       "expr": "trino_execution_QueryManager_WallInputBytesRate_OneMinute_Max{app=~\"$cluster\"} offset 7d",
       "legendFormat": "{{app}}-七日前"
      }
     ]
    },
    {
     "title": "近一分钟完成Query平均执行时间",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "trino_execution_QueryManager_ExecutionTime_OneMinute_Avg{app=~\"$cluster\"}",
       "legendFormat": "{{app}}-今日"
      },
      {
       "expr": "trino_execution_QueryManager_ExecutionTime_OneMinute_Avg{app=~\"$cluster\"} offset 1d",
       "legendFormat": "{{app}}-昨日"
      },
      {
       "expr": "trino_execution_QueryManager_ExecutionTime_OneMinute_Avg{app=~\"$cluster\"} offset 7d",
       "legendFormat": "{{app}}-七日前"
      }
     ]
    },
    {
     "title": "近一分钟完成Query最大执行时间",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "trino_execution_QueryManager_ExecutionTime_OneMinute_Max{app=~\"$cluster\"}",
       "legendFormat": "{{app}}-今日"
      },
      {
       "expr": "trino_execution_QueryManager_ExecutionTime_OneMinute_Max{app=~\"$cluster\"}  offset 1d",
       "legendFormat": "{{app}}-昨日"
      },
      {
       "expr": "trino_execution_QueryManager_ExecutionTime_OneMinute_Max{app=~\"$cluster\"} offset 7d",
       "legendFormat": "{{app}}-七日前"
      }
     ]
    }
   ]
  }
 ]
}