{
 "title": "Chaos Mesh Overview",
 "description": "Overview for monitoring Chaos Mesh. \r\n\r\nProviding active chaos experiments, instances of each components, and experiments activity events. ",
 "tags": [
  "adhar",
  "application",
  "chaos-mesh"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Data source", "query": "prometheus" },
   {
    "name": "Namespace",
    "label": "Chaos Mesh Namespace",
    "query": {
     "query": "label_values(chaos_mesh_templates, namespace)"
    }
   },
   {
    "name": "ControllerManager",
    "label": "Controller Manager",
    "query": {
     "query": "label_values(up{namespace=\"$Namespace\", service=\"chaos-mesh-controller-manager\"}, pod)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Chaos Experiments", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Experiments",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(chaos_controller_manager_chaos_experiments{namespace=\"$Namespace\", pod=\"$ControllerManager\"})",
     "legendFormat": "Active"
    }
   ]
  },
  {
   "title": "Schedules",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(chaos_controller_manager_chaos_schedules{namespace=\"$Namespace\", pod=\"$ControllerManager\"})",
     "legendFormat": "Workflow"
    }
   ]
  },
  {
   "title": "Workflows",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(chaos_controller_manager_chaos_workflows{namespace=\"$Namespace\", pod=\"$ControllerManager\"})",
     "legendFormat": "Workflow"
    }
   ]
  },
  {
   "title": "Experiments Types",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum by (kind)(chaos_controller_manager_chaos_experiments{namespace=\"$Namespace\", pod=\"$ControllerManager\"})",
     "legendFormat": "{{kind}}"
    }
   ]
  },
  { "title": "Chaos Mesh Activities", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Experiments Events",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "delta(chaos_controller_manager_emitted_event_total{namespace=\"$Namespace\",pod=\"$ControllerManager\"}[$__rate_interval])",
     "legendFormat": "{{reason}}"
    }
   ]
  },
  { "title": "Chaos Mesh Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Controller Manager Instances",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(up{namespace=\"$Namespace\", service=\"chaos-mesh-controller-manager\"})"
    }
   ]
  },
  {
   "title": "Chaos Daemon Instances",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(up{namespace=\"$Namespace\", service=\"chaos-daemon\"})"
    }
   ]
  },
  {
   "title": "Chaos Dashboard Instances",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(up{namespace=\"$Namespace\", service=\"chaos-dashboard\"})"
    }
   ]
  }
 ]
}