apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cluster-sample
spec:
  instances: 3
  logLevel: info
  primaryUpdateStrategy: unsupervised
  storage:
    size: 1Gi
  walStorage:
    size: 1Gi