apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: compositesecretrotation-aws
  labels:
    feature: secretrotation
    provider: aws
spec:
  compositeTypeRef:
    apiVersion: platform.adhar.io/v1alpha1
    kind: CompositeSecretRotation
  mode: Pipeline
  pipeline:
    - step: render-rotation
      functionRef:
        name: function-kcl
      input:
        apiVersion: krm.kcl.dev/v1alpha1
        kind: KCLRun
        spec:
          source: |
            oxr = option("params").oxr
            ocds = option("params").ocds
            
            params = oxr.spec.parameters
            metadata = oxr.metadata
            providerConfigName = oxr.spec.providerConfigRef?.name or "default"
            
            # Rotation configuration
            secretType = params.secretType
            rotationSchedule = params.rotationSchedule or "0 0 * * 0"
            rotationPeriodDays = params.rotationPeriodDays or 30
            automaticRotation = params.automaticRotation or True
            secretReferences = params.secretReferences or []
            targetServices = params.targetServices or []
            
            # Notification and hooks
            notificationConfig = params.notificationConfig or {}
            preRotationHooks = params.preRotationHooks or []
            postRotationHooks = params.postRotationHooks or []
            
            # Retention and encryption
            retentionPolicy = params.retentionPolicy or {}
            keepVersions = retentionPolicy.keepVersions or 3
            encryption = params.encryption or {}
            enableEncryption = encryption.enabled or True
            kmsKeyId = encryption.kmsKeyId or ""
            
            # Audit
            auditConfig = params.auditConfig or {}
            enableAudit = auditConfig.enabled or True
            
            tags = params.tags or {}
            deletionPolicy = params.deletionPolicy or "Delete"
            
            _items = [
                {
                    apiVersion: "kubernetes.crossplane.io/v1alpha1"
                    kind: "Object"
                    metadata.name: "rotation-cronjob"
                    metadata.labels: {
                        feature: "secretrotation"
                        provider: "aws"
                    }
                    spec: {
                        forProvider: {
                            manifest: {
                                apiVersion: "batch/v1"
                                kind: "CronJob"
                                metadata: {
                                    name: metadata.name
                                    namespace: "adhar-system"
                                    labels: {
                                        "app.kubernetes.io/name": "secret-rotation"
                                        "app.kubernetes.io/managed-by": "adhar"
                                    }
                                }
                                spec: {
                                    schedule: rotationSchedule
                                    suspend: not automaticRotation
                                    jobTemplate: {
                                        spec: {
                                            template: {
                                                spec: {
                                                    serviceAccountName: "secret-rotation"
                                                    containers: [{
                                                        name: "rotator"
                                                        image: "amazon/aws-secretsmanager-agent:latest"
                                                        env: [
                                                            {
                                                                name: "SECRET_TYPE"
                                                                value: secretType
                                                            },
                                                            {
                                                                name: "ROTATION_DAYS"
                                                                value: str(rotationPeriodDays)
                                                            },
                                                            {
                                                                name: "KEEP_VERSIONS"
                                                                value: str(keepVersions)
                                                            }
                                                        ]
                                                        command: ["/bin/sh", "-c"]
                                                        args: ["""
                                                          echo 'Starting secret rotation...'
                                                          for secret in ${SECRETS}; do
                                                            aws secretsmanager rotate-secret --secret-id $secret --rotation-lambda-arn ${LAMBDA_ARN}
                                                          done
                                                        """]
                                                    }]
                                                    restartPolicy: "OnFailure"
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                        }
                        providerConfigRef.name: providerConfigName
                    }
                },
                {
                    apiVersion: "kubernetes.crossplane.io/v1alpha1"
                    kind: "Object"
                    metadata.name: "rotation-lambda"
                    metadata.labels: {
                        feature: "secretrotation"
                        provider: "aws"
                    }
                    spec: {
                        forProvider: {
                            manifest: {
                                apiVersion: "lambda.aws.crossplane.io/v1alpha1"
                                kind: "Function"
                                metadata: {
                                    name: "${metadata.name}-rotator"
                                    namespace: "adhar-system"
                                }
                                spec: {
                                    forProvider: {
                                        role: "arn:aws:iam::ACCOUNT:role/SecretsManagerRotation"
                                        runtime: "python3.11"
                                        handler: "lambda_function.lambda_handler"
                                        code: {
                                            zipFile: """
import boto3
import json

def lambda_handler(event, context):
    secret_id = event['SecretId']
    token = event['ClientRequestToken']
    step = event['Step']
    
    secrets_client = boto3.client('secretsmanager')
    
    if step == 'createSecret':
        # Generate new secret
        new_secret = generate_new_secret()
        secrets_client.put_secret_value(
            SecretId=secret_id,
            ClientRequestToken=token,
            SecretString=new_secret,
            VersionStages=['AWSPENDING']
        )
    elif step == 'setSecret':
        # Update target with new secret
        update_target(secret_id, token)
    elif step == 'testSecret':
        # Test new secret
        test_secret(secret_id, token)
    elif step == 'finishSecret':
        # Finalize rotation
        secrets_client.update_secret_version_stage(
            SecretId=secret_id,
            VersionStage='AWSCURRENT',
            MoveToVersionId=token
        )
    
    return {'statusCode': 200}

def generate_new_secret():
    import string
    import random
    return ''.join(random.choices(string.ascii_letters + string.digits, k=32))

def update_target(secret_id, token):
    pass

def test_secret(secret_id, token):
    pass
                                            """
                                        }
                                        timeout: 300
                                    }
                                }
                            }
                        }
                        providerConfigRef.name: providerConfigName
                    }
                }
            ]
            
            # Add service restart jobs if needed
            for idx, service in targetServices:
                if service.restartOnRotation:
                    _items += [{
                        apiVersion: "kubernetes.crossplane.io/v1alpha1"
                        kind: "Object"
                        metadata.name: "restart-{}-{}".format(service.name, idx)
                        metadata.labels: {
                            feature: "secretrotation"
                            component: "restart"
                        }
                        spec: {
                            forProvider: {
                                manifest: {
                                    apiVersion: "batch/v1"
                                    kind: "Job"
                                    metadata: {
                                        name: "restart-${service.name}"
                                        namespace: service.namespace or "default"
                                    }
                                    spec: {
                                        template: {
                                            spec: {
                                                containers: [{
                                                    name: "kubectl"
                                                    image: "bitnami/kubectl:latest"
                                                    command: ["kubectl", "rollout", "restart", "deployment/${service.name}"]
                                                }]
                                                restartPolicy: "Never"
                                            }
                                        }
                                    }
                                }
                            }
                            providerConfigRef.name: providerConfigName
                        }
                    }]
            
            # Get observed state
            _observedResources = ocds or {}
            _cronjobObserved = _observedResources.get("rotation-cronjob", {}).get("resource", {})
            _cronjobStatus = _cronjobObserved.get("status", {})
            
            _phase = "Pending"
            _message = "Secret rotation policy created"
            _ready = False
            _lastRotationTime = ""
            
            if _cronjobStatus:
                _lastSuccessfulTime = _cronjobStatus.get("lastSuccessfulTime", "")
                _lastScheduleTime = _cronjobStatus.get("lastScheduleTime", "")
                
                if _lastSuccessfulTime:
                    _phase = "Active"
                    _message = "Secret rotation is active"
                    _ready = True
                    _lastRotationTime = _lastSuccessfulTime
                elif automaticRotation:
                    _phase = "Active"
                    _message = "Waiting for next rotation"
                    _ready = True
                else:
                    _phase = "Paused"
                    _message = "Automatic rotation is disabled"
                    _ready = True
            
            items = _items + [{
                apiVersion: "platform.adhar.io/v1alpha1"
                kind: "CompositeSecretRotation"
                metadata: oxr.metadata
                status: {
                    phase: _phase
                    message: _message
                    ready: _ready
                    if _lastRotationTime:
                        lastRotationTime: _lastRotationTime
                }
            }]

