apiVersion: v1
kind: ConfigMap
metadata:
  name: workflow-controller-configmap
  namespace: argo
data:
  config: |
    sso:
      insecureSkipVerify: true 
      issuer: https://adhar.localtest.me:8443/keycloak/realms/adhar
      clientId:
        name: keycloak-oidc
        key: client-id
      clientSecret:
        name: keycloak-oidc
        key: secret-key
      redirectUrl: https://adhar.localtest.me:8443/argo-workflows/oauth2/callback
      rbac:
        enabled: true
      scopes:
        - openid
        - profile
        - email
        - groups
    nodeEvents:
      enabled: false