bases:
  - snippets/defaults.yaml
---
bases:
  - snippets/env.gotmpl
---
bases:
  - snippets/derived.gotmpl
---
{{ readFile "snippets/templates.gotmpl" }}
{{- $v := .Values }}
{{- $a := $v.apps }}

releases:
  - name: adhar-api
    installed: false
    namespace: adhar-system
    labels:
      pkg: adhar
    <<: *default
  - name: adhar-console
    installed: true
    namespace: adhar-system
    labels:
      pkg: adhar
    <<: *default