apiVersion: platform.adhar.io/v1alpha1
kind: Cluster
metadata:
  name: alpha-prod-usw2-eks-01
  labels:
    platform.adhar.io/environment-type: production
spec:
  parameters:
    displayName: Alpha Corp Production EKS Cluster (US-West-2)
    organizationRef:
      name: org-alpha-corp
    environmentType: production
    provider: AWS_EKS
    region: us-west-2
    version: "1.28"
    controlPlane:
      highAvailability: true
      endpointAccess: PublicAndPrivate
      iamRoles:
        clusterRoleARN: arn:aws:iam::123456789012:role/AdharAlphaProdEKSClusterRole
        nodeRoleARN: arn:aws:iam::123456789012:role/AdharAlphaProdEKSNodeRole
    nodePools:
      - name: general-purpose-app
        instanceType: m5.xlarge
        count: 3
        minCount: 2
        maxCount: 5
        storageSize: "100"
        labels:
          nodepool-type: application
          workload: general
      - name: critical-services
        instanceType: r5.large
        count: 2
        minCount: 2
        maxCount: 3
        storageSize: "80"
        taints:
          - key: CriticalServiceOnly
            effect: NoSchedule
    networkConfig:
      vpcId: vpc-alphaprodusw2
      subnetIds:
        - subnet-alphaprodusw2a
        - subnet-alphaprodusw2b
        - subnet-alphaprodusw2c
      podCidrBlock: 10.100.0.0/16
      serviceCidrBlock: 10.101.0.0/16
      cniPlugin: aws-vpc-cni
    addons:
      enableClusterAutoscaler: true
      enableMetricsServer: true
  writeConnectionSecretToRef:
    name: alpha-prod-usw2-eks-01-kubeconfig
    namespace: crossplane-system
