# Kyverno Helm Chart Values

# Kyverno policies configuration
policies:
  podSecurityStandard: restricted
  validationFailureAction: Audit #Audit/Enforce
  podSecuritySeverity: High

# Additional Kyverno configuration
replicaCount: 1

resources:
  requests:
    memory: 64Mi
    cpu: 100m
  limits:
    memory: 128Mi
    cpu: 200m