---
# Source: gitea/charts/redis-cluster/templates/redis-serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: gitea-redis-cluster
  namespace: "default"
  labels:
    app.kubernetes.io/instance: gitea
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: redis-cluster
    app.kubernetes.io/version: 7.4.2
    helm.sh/chart: redis-cluster-11.4.3
automountServiceAccountToken: false
