cluster:
  name: adhar
  provider: civo
  domainSuffix: cloud.adhar.io
otomi:
  hasExternalDNS: true
dns:
  domainFilters:
    - cloud.adhar.io
  provider:
    civo:
      apiToken: 'ADD-YOUR-CIVO-API-TOKEN-HERE'
apps:
  cert-manager:
    issuer: letsencrypt
    stage: production
    email: admin@adhar.io
